name: Add JIRA Priority Label

on:
  pull_request:
    types: [opened, synchronize]
env:
  ENVIRONMENT: JIRA_ACCESS_TOKEN

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Validate Secrets
        run: |
          echo "JIRA_USERNAME: ${JIRA_USERNAME:0:2}***"
          echo "JIRA_API_TOKEN: ${JIRA_API_TOKEN:0:2}***"
          echo "JIRA_BASE_URL: ${JIRA_BASE_URL:0:2}***"
          echo "BASIC_AUTH_TOKEN: ${BASIC_AUTH_TOKEN:0:2}***"
          echo "All required secrets are set."
        shell: bash

      - name: Extract JIRA Ticket ID
        id: extract_ticket_id
        run: |
          PRIORITY=${{ env.priority }}
          LABEL=""
          if [[ "$PRIORITY" == "High" ]]; then
            LABEL="high-priority"
            gh pr edit ${{ github.event.pull_request.number }} --add-label $LABEL
            echo "Added high-priority label to PR #${{ github.event.pull_request.number }}"
          else
            echo "No label added because priority is not High."
          fi
        shell: bash

      - name: Get JIRA Ticket Priority
        id: get_ticket_priority
        run: |
          TICKET_ID=${{ steps.extract_ticket_id.outputs.ticket_id }}
          RESPONSE=$(curl -s \
                      -H "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}" \
                      -H "Accept: application/json" \
                      ${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/$TICKET_ID)
          echo "JIRA API response: $RESPONSE"
          PRIORITY=$(echo $RESPONSE | jq -r .fields.priority.name)
          if [[ "$PRIORITY" == "null" ]]; then
            echo "Error fetching JIRA ticket priority. Response: $RESPONSE"
            exit 1
          fi
          echo "priority=${PRIORITY}" >> $GITHUB_ENV
        shell: bash

      - name: Set PR Label
        run: |
          echo ${{ env.priority }}
          PRIORITY=${{ env.priority }}
          if [[ "$PRIORITY" == "High" ]]; then
            LABEL="high-priority"
            gh pr edit ${{ github.event.pull_request.number }} --add-label $LABEL
            echo "Added high-priority label to PR #${{ github.event.pull_request.number }}"
          else
            echo "No label added because priority is not High."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
